name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt install -y doxygen
      - uses: actions/checkout@v4
      - name: configure
        run: cmake -S . -B build
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
      - name: docs
        run: cmake --build build --target docs
